version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:30"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 1
    open-pull-requests-limit: 5
    assignees:
      - "shm11C3"
    groups:
      default:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
        exclude-patterns:
          - "@biomejs/biome"
      biome:
        patterns:
          - "@biomejs/biome"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 3
    assignees:
      - "shm11C3"
